# Generated by Django 3.2.19 on 2025-11-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
                ('basic_wind_speed', models.FloatField(blank=True, null=True)),
                ('seismic_zone', models.CharField(blank=True, max_length=8)),
                ('seismic_factor', models.FloatField(blank=True, null=True)),
                ('max_temp', models.FloatField(blank=True, null=True)),
                ('min_temp', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'district'],
                'unique_together': {('state', 'district')},
            },
        ),
    ]
