# Generated by Django 3.2.19 on 2025-11-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('girder_steel', 'Girder steel'), ('cross_bracing_steel', 'Cross bracing steel'), ('deck_concrete', 'Deck concrete')], max_length=32)),
                ('grade', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'grade'],
                'unique_together': {('category', 'grade')},
            },
        ),
    ]
